name: deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - run: |
      #     echo $USER
      #     echo $PATH
      #     echo "$(whereis pm2)"
      #     echo "$(which pm2)"
      #     npm i
      #     cd client
      #     npm i
      #     npm run build
      #     cd ..
      #     pm2 stop 1
      #     pm2 stop 2
      #     pm2 start 1
      #     pm2 start 2
      #     pm2 save
      #     sudo service nginx restart

      - run: |
          bash -leo << 'EOF'
          echo $USER
          echo $PATH
          echo "$(whereis pm2)"
          echo "$(which pm2)"
          npm i
          cd client
          npm i
          npm run build
          cd ..
          pm2 stop 1
          pm2 stop 2
          pm2 start 1
          pm2 start 2
          pm2 save
          sudo service nginx restart
          EOF
